### ISSUE TITLE
File is empty after running FiletypeFormat

### ISSUE THREAD

**Issue by caioariede** [pappasam/vim-filetype-formatter#4]
I'm really interested in using this plugin but whenever I try to manually call `FiletypeFormat` (or even using mappings) it clears the current buffer.

I'm using Vim 8.1 and black.

Any thoughts?

**Comment by pappasam** [comment]
@caioariede thanks for raising; hopefully we can resolve!

I've honestly only tested this on Neovim; I just downloaded Vim 8 and can confirm this issue

**Comment by caioariede** [comment]
Thanks man, I was going to take a look and see if I could fix it myself but I think you might have some ideas on what it is. This plugin will save my life, thank you for doing it. :)

**Comment by pappasam** [comment]
@caioariede done, try again and let me know if it works (make sure to update to latest version)

**Comment by caioariede** [comment]
Worked like a charm!! thanks
